POST http://localhost:5076/signup HTTP/1.1
content-type: application/json

{
    "Fullname": "Hasin",
    "Email":"ammi@gmail.com",
    "Phone":"6788",
    "Address":"36 Green Road",
    "Password": "123456",
    "Role": "Chef"
}

###
POST http://localhost:5076/signin HTTP/1.1
content-type: application/json

{
    "Email":"hasin@gmail.com",
    "Password": "1234567"
}
###

GET https://localhost:7262/getallcomments/31 HTTP/1.1
content-type: application/json
###


PUT https://localhost:7262/update-userdetails HTTP/1.1
content-type: application/json

{
    "UID":2,
    "Address":"123456",
    "Phone":"1234567",
    "PhotoURL":"url"
}